
before_script:
    - apt-get update -yqq
    - apt-get install cmake gcc g++ -yqq
    - apt-get install bison -yqq

antetest:
    script:
        - cmake .
        - cmake --build .
        - ./antetests

