
before_script:
    - apt-get update -yqq
    - add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - apt-get update -yqq
    - apt-get install cmake gcc-7 g++-7 bison -yqq

antetest:
    script:
        - cmake .
        - cmake --build .
        - ./antetests

